Repository DevFTB/Moonbeam-Meadows, pull requests merged in 2023-04, with the labels that each got.

#8 Base questing system
  Level/Crops/CropEntity.gd
  Level/Level.gd
  Level/Quests/QuestGUI.gd
  Level/Quests/QuestManager.gd
  Level/Quests/QuestResource.gd
  Level/Quests/QuestsGUI.gd
  Level/Quests/quest_campaign_1.tres
  Level/Quests/quest_campaign_2.tres
  Level/Quests/quest_display.tscn
  Level/moon.tscn
  Player/InventoryComponent.gd
Labels: feature

#10 Quest completion and chaining
  GUI/InventoryGUI.gd
  Level/Quests/QuestGUI.gd
  Level/Quests/QuestManager.gd
  Level/Quests/QuestResource.gd
  Level/Quests/QuestsGUI.gd
  Level/moon.tscn
  Player/InventoryComponent.gd
Labels: improvement

#11 Currency system and currency quest rewards
  GUI/PhoneGUI.gd
  Level/Crops/CropResource.gd
  Level/Currency/CurrencyManager.gd
  Level/Currency/unicoin_sprite.png
  Level/Currency/unicoin_sprite.png.import
  Level/CurrencyGUI.gd
  Level/Quests/CurrencyQuestReward.gd
  Level/Quests/QuestGUI.gd
  Level/Quests/QuestManager.gd
  Level/Quests/QuestResource.gd
  Level/Quests/QuestReward.gd
  Level/Quests/QuestsGUI.gd
  Level/Quests/quest_campaign_1.tres
  Level/Quests/quest_campaign_2.tres
  Level/Quests/quest_display.tscn
  Level/moon.tscn
  Player/Player.gd
Labels: feature, improvement

#14 Better Rewards Text
  Level/Quests/CurrencyQuestReward.gd
  Level/Quests/QuestResource.gd
  Level/Quests/QuestReward.gd
Labels: improvement

#17 Quest Completion Fix
  Level/Level.gd
  Level/Quests/CurrencyQuestReward.gd
  Level/Quests/QuestResource.gd
  Level/Quests/QuestsGUI.gd
  Level/moon.tscn
Labels: bug

#18 Crop growth
  Level/Crops/CropEntity.gd
  Level/Crops/CropResource.gd
  Level/Crops/Resources/crop_moon_wheat.tres
  Level/Crops/crop_entity.tscn
  Level/Level.gd
  Level/Quests/CurrencyQuestReward.gd
Labels: feature
